version: '3.1'
services:
  elasticsearch:
    image: elasticsearch:8.6.2
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
     - discovery.type=single-node
     - cluster.name=my
     - xpack.security.enabled:true